name: Deploy Docusaurus

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
    - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Node.js のセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 18  # 使用するNode.jsのバージョン

      - name: 依存関係のインストール
        run: npm install

      - name: Docusaurus のビルド
        run: npm run build

      - name: GitHub Pages にデプロイ
        env:
          GIT_USER: github-actions[bot]
          USE_SSH: false
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # SecretsにPATを設定
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Deploy the build to GitHub Pages
          npm run deploy
